import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/Toast";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-gradient-to-r from-[#d1208a43] via-[#ffb30051] to-[#CAEEF580]`}
        >
          <Header />
          <div className="bg-[#D1208A80] opacity-70 pt-0.5"></div>
          <main>{children}</main>
          <Toaster position="top-right" theme="light" richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
